name: Sync component versions

on:
  schedule:
    - cron: '15 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: romoh/dependencies-autoupdate@v1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: 'make --always-make jsonnet/kube-prometheus/versions.json'
        on-changes-command: 'make --always-make generate'
