name: Sync component versions

on:
  schedule:
    - cron: '15 * * * *'
  push:
    branch: main
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: romoh/dependencies-autoupdate@v1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "'scripts/generate-versions.sh $token > jsonnet/kube-prometheus/versions.json'"
        on-changes-command: "'make --always-make generate'"
